version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - front
  front:
    container_name: front
    build:
      context: ./front/
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000
    volumes:
      - ./front:/front
    # 開発時用のコマンドのため本番環境では変更する
    command: yarn run dev
  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3001:3000"
    volumes:
      - ./api:/api
