version: '3'

services:
  front:
    container_name: front
    build: 
      context: ./front/
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front
  api:
    container_name: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3001:3000"
    volumes:
      - ./api:/api
